### ISSUE TITLE
secp256k1 unit tests dont compile

### ISSUE THREAD

**Issue by kevoh1516** [scrtlabs/secret-toolkit#58]
I ran into this issue because I was trying to unit test my own functions which rely on secp256k1. It looks like the sign and verify functions need `deps.api` to be given as input. But even after I gave it as input it still fails during runtime because the mock version of dependencies spits out an empty array when you sign something which secp256k1 doesn't like at all. Is there any workaround for this? Or a simple fix?

**Comment by reuvenpo** [comment]
We need to add this functionality to our cosmwasm_std fork [here](https://github.com/scrtlabs/SecretNetwork/blob/7f062dd30178ecf40278b770785f488d06eaef38/cosmwasm/packages/std/src/mock.rs#L116)

If you need this now as fast as possible, my best suggestion is to make your own [fn mock_dependencies](https://github.com/scrtlabs/SecretNetwork/blob/7f062dd30178ecf40278b770785f488d06eaef38/cosmwasm/packages/std/src/mock.rs#L26) which returns an instance of a type similar to [MockApi](https://github.com/scrtlabs/SecretNetwork/blob/7f062dd30178ecf40278b770785f488d06eaef38/cosmwasm/packages/std/src/mock.rs#L59), which includes correct implementations of those encryption interfaces in its `Api` trait implementation. Then use your new function instead of the regular one.

If you don't want to do this, the easier solution is to write integration tests for your contract which run on [LocalSecret](https://docs.scrt.network/secret-network-documentation/development/tools-and-libraries/local-secret), but they will run much slower.

CC @assafmo

**Comment by Cashmaney** [comment]
This got fixed at some point
